# Generated by Django 5.0.9 on 2026-09-17 08:04

import apps.remover.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=apps.remover.models.upload_path)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=apps.remover.models.processed_path)),
                ('background_type', models.CharField(choices=[('transparent', 'Transparent'), ('color', 'Solid colour'), ('image', 'Custom background image')], default='transparent', max_length=20)),
                ('background_color', models.CharField(blank=True, default='', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
